#!/bin/bash
# Test script for status exchange between wallbox and simulator

echo "========================================"
echo "Status Exchange Test"
echo "========================================"
echo ""
echo "This test will verify the status exchange between wallbox and simulator"
echo ""
echo "Instructions:"
echo "1. Terminal 1: Run './simulator' in build/ directory"
echo "2. Terminal 2: Run './wallbox_control_v3' in build/ directory"
echo ""
echo "Test scenarios:"
echo "==============="
echo ""
echo "Scenario 1: Simulator initiates charging"
echo "  In simulator: type 'ready' -> watch wallbox respond"
echo "  In simulator: type 'charge' -> watch wallbox start charging"
echo ""
echo "Scenario 2: Wallbox initiates charging"
echo "  In wallbox: type 'start' -> watch simulator respond"
echo "  In wallbox: type 'stop' -> watch simulator respond"
echo ""
echo "Scenario 3: Enable/Disable cycle"
echo "  In wallbox: type 'disable' -> simulator commands should be rejected"
echo "  In wallbox: type 'enable' -> simulator commands should work again"
echo ""
echo "Expected behavior:"
echo "- Status messages exchanged every 100ms"
echo "- State changes reflected immediately in both systems"
echo "- Relay state synchronized between wallbox and simulator"
echo "- Disable/enable properly blocks/allows commands"
echo ""
echo "Verification points:"
echo "✓ [WALLBOX → SIMULATOR] messages appear when wallbox sends status"
echo "✓ [SIMULATOR → WALLBOX] messages appear when simulator sends status"
echo "✓ State transitions are logged on both sides"
echo "✓ Relay changes trigger appropriate state updates"
echo ""
