#!/bin/bash
# Test State Synchronization Between Wallbox and Simulator

echo "=========================================="
echo "State Synchronization Test"
echo "=========================================="
echo ""
echo "This test demonstrates that the simulator"
echo "automatically synchronizes its state when"
echo "the wallbox changes state."
echo ""
echo "Test Steps:"
echo "1. Start both programs"
echo "2. In wallbox, type: start"
echo "   → Simulator should auto-change to CHARGING"
echo "3. In wallbox, type: pause"
echo "   → Simulator should auto-change to READY"
echo "4. In wallbox, type: stop"
echo "   → Simulator should auto-change to IDLE"
echo "5. In wallbox, type: disable"
echo "   → Simulator should show DISABLED status"
echo "6. In wallbox, type: enable"
echo "   → Simulator should show ENABLED status"
echo ""
echo "Expected Output in Simulator:"
echo "  [WALLBOX → SIMULATOR] State sync request: idle → charging"
echo "  [WALLBOX → SIMULATOR] State sync request: charging → ready"
echo "  [WALLBOX → SIMULATOR] State sync request: ready → idle"
echo ""
echo "=========================================="
echo "Ready to test!"
echo "=========================================="
echo ""
echo "Terminal 1: cd /Users/achraf/pro/PJMT/WallboxCtrl/build && ./simulator"
echo "Terminal 2: cd /Users/achraf/pro/PJMT/WallboxCtrl/build && ./wallbox_control_v4"
echo ""
